#!/usr/bin/env python

import sys, os, re, subprocess

os.environ["COMPOSER_HOME"] = "/htdocs/dev/repo/.composer"

previous_head = sys.argv[1]
new_head = sys.argv[2]
is_branch_checkout = sys.argv[3]

if is_branch_checkout == "0":
	sys.exit(0)

# composer install
if not subprocess.call(['composer', 'install', '--no-dev']):
	print "composer install completed!"

# bower install
if not subprocess.call(['bower', 'install', '-p', '--allow-root'], cwd='static/books'):
	print "bower install completed!"

